### ISSUE TITLE
add koa backend

### ISSUE THREAD

**Issue by kalmanb** [movio/movio-todomvc#14]

**Comment by d4ncer** [comment]
What is the goal of `koa` here? As a mock server or an extension of `webpack-dev-server`?

**Comment by kalmanb** [comment]
Was thinking mock server - maybe not needed - should we just use WDS?
I suppose it might help if putting lots of logic in the mocked backend - but for frontend dev - probably not needed.

I'm also thinking about generating the mocked backend with apidoc...

**Comment by kalmanb** [comment]
Getting rid of this for now.
